# This is a basic workflow to help you get started with Actions

name: shared-jobs-build-ci

# Controls when the workflow will run
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      node-version:
        description: "Node version"
        required: true
        type: string
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone repository
      uses: actions/checkout@v2
        
    - name: build image
      run: |
        docker build . --file Dockerfile --tag test:app
    

